Run_loot_table = {

    {["itemId"] = "30242", ["itemName"] = "helm of the vanquished champion", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Resto):P3\nPaladin (Holy):P2\nChaman (Enh):P2\nPaladin ( Tank):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30243", ["itemName"] = "helm of the vanquished defender", ["classPriority"] = "Druide (Tank):P2\nDruide (Heal):P2\nPrêtre (Holy):P3\nDruide (Equi):P2\nGuerrier (Tank):P2\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "30249", ["itemName"] = "pauldrons of the vanquished defender", ["classPriority"] = "Druide (Tank):P2\nDruide (Heal):P2\nPrêtre (Holy):P3\nDruide (Equi):P2\nGuerrier (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "30237", ["itemName"] = "chestguard of the vanquished defender", ["classPriority"] = "Druide (Tank):P2\nDruide (Heal):P2\nPrêtre (Holy):P3\nGuerrier (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "30246", ["itemName"] = "leggings of the vanquished defender", ["classPriority"] = "Druide (Tank):P2\nPrêtre (Holy):P3\nGuerrier (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "32385", ["itemName"] = "magtheridons head", ["classPriority"] = "Prêtre (SP):P1\nPaladin (Holy):P1\nPrêtre (Holy):P1\nMage(Arcane):P1\nDruide (Equi):P2\nChasseur (Surv):P3\nChasseur (Prec):P2\nPaladin ( Tank):P1\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "31089", ["itemName"] = "chestguard of the forgotten conqueror", ["classPriority"] = "Prêtre (SP):P3\nPaladin (Holy):P3\nPrêtre (Holy):P4\nPaladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32405", ["itemName"] = "verdant sphere", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P2\nDruide (Heal):P2\nPrêtre (Holy):P2\nMage(Arcane):P3\nDruide (Equi):P2\nGuerrier (Tank):P2\nChaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P3\nChasseur (Prec):P2\nChaman (Elem):P3\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30248", ["itemName"] = "pauldrons of the vanquished champion", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30236", ["itemName"] = "chestguard of the vanquished champion", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P2\nChaman (Enh):P2\nChaman (Elem):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "29760", ["itemName"] = "helm of the fallen champion", ["classPriority"] = "Paladin (Holy):P1\nChaman (Enh):P1\nPaladin ( Tank):P1\nChaman (Elem):P2\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "29763", ["itemName"] = "pauldrons of the fallen champion", ["classPriority"] = "Paladin (Holy):P1\nChaman (Enh):P1\nPaladin ( Tank):P2\nChaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "30245", ["itemName"] = "leggings of the vanquished champion", ["classPriority"] = "Paladin (Holy):P2\nChaman (Enh):P2\nPaladin ( Tank):P2\nChaman (Elem):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "29764", ["itemName"] = "pauldrons of the fallen defender", ["classPriority"] = "Druide (Heal):P1\nPrêtre (Holy):P1\nGuerrier (Fury:P1\nDuide (Cat):P1", ["note"] = "",},
    {["itemId"] = "29761", ["itemName"] = "helm of the fallen defender", ["classPriority"] = "Prêtre (Holy):P1\nGuerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "30240", ["itemName"] = "gloves of the vanquished defender", ["classPriority"] = "Prêtre (Holy):P3\nDruide (Equi):P2\nGuerrier (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "31097", ["itemName"] = "helm of the forgotten conqueror", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "29759", ["itemName"] = "helm of the fallen hero", ["classPriority"] = "Mage(Arcane):P1\nDémo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P2\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29762", ["itemName"] = "pauldrons of the fallen hero", ["classPriority"] = "Mage(Arcane):P1\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P1", ["note"] = "",},
    {["itemId"] = "30244", ["itemName"] = "helm of the vanquished hero", ["classPriority"] = "Mage(Arcane):P2\nChasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30247", ["itemName"] = "leggings of the vanquished hero", ["classPriority"] = "Mage(Arcane):P2\nChasseur (Surv):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30250", ["itemName"] = "pauldrons of the vanquished hero", ["classPriority"] = "Mage(Arcane):P3\nChasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30238", ["itemName"] = "chestguard of the vanquished hero", ["classPriority"] = "Mage(Arcane):P3\nChasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "30239", ["itemName"] = "gloves of the vanquished champion", ["classPriority"] = "Chaman (Enh):P2\nPaladin ( Tank):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30241", ["itemName"] = "gloves of the vanquished hero", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Prec):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "29766", ["itemName"] = "leggings of the fallen champion", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "29755", ["itemName"] = "chestguard of the fallen hero", ["classPriority"] = "Démo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1", ["note"] = "",},
    {["itemId"] = "29756", ["itemName"] = "gloves of the fallen hero", ["classPriority"] = "Démo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29073", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P1", ["note"] = "",},
    {["itemId"] = "28745", ["itemName"] = "mithril chain of heroism", ["classPriority"] = "Paladin ( Ret):P1", ["note"] = "",},
    {["itemId"] = "28777", ["itemName"] = "cloak of the pit stalker", ["classPriority"] = "Paladin ( Ret):P1", ["note"] = "",},
    {["itemId"] = "28795", ["itemName"] = "bladespire warbands", ["classPriority"] = "Paladin ( Ret):P1\nGuerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28779", ["itemName"] = "girdle of the endless pit", ["classPriority"] = "Paladin ( Ret):P1\nGuerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28608", ["itemName"] = "ironstriders of urgency", ["classPriority"] = "Paladin ( Ret):P1", ["note"] = "",},
    {["itemId"] = "28830", ["itemName"] = "dragonspine trophy", ["classPriority"] = "Paladin ( Ret):P1\nDruide (Tank):P2\nGuerrier (Tank):P1\nChaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P3\nChasseur (Prec):P3\nGuerrier (Fury:P3\nDuide (Cat):P1\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "28773", ["itemName"] = "gorehowl", ["classPriority"] = "Paladin ( Ret):P1", ["note"] = "",},
    {["itemId"] = "30022", ["itemName"] = "pendant of the perilous", ["classPriority"] = "Paladin ( Ret):P2\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "30098", ["itemName"] = "razor scale battlecloak", ["classPriority"] = "Paladin ( Ret):P2", ["note"] = "",},
    {["itemId"] = "30102", ["itemName"] = "krakken heart breastplate", ["classPriority"] = "Paladin ( Ret):P2", ["note"] = "",},
    {["itemId"] = "30057", ["itemName"] = "bracers of eradication", ["classPriority"] = "Paladin ( Ret):P2\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "29947", ["itemName"] = "gloves of the searing grip", ["classPriority"] = "Paladin ( Ret):P2\nDruide (Tank):P2\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "30106", ["itemName"] = "belt of one hundred deaths", ["classPriority"] = "Paladin ( Ret):P2\nDruide (Tank):P2\nChaman (Enh):P3\nChasseur (BM):P2\nChasseur (Surv):P2\nGuerrier (Fury:P2\nGuerrier (Fury:P3\nDuide (Cat):P3\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "29997", ["itemName"] = "band of the ranger general", ["classPriority"] = "Paladin ( Ret):P2\nDruide (Tank):P2\nChaman (Enh):P2\nChasseur (BM):P2\nChasseur (Prec):P2\nGuerrier (Fury:P2\nDuide (Cat):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "29995", ["itemName"] = "leggings of murderous intent", ["classPriority"] = "Paladin ( Ret):P2\nChasseur (BM):P2\nChasseur (Prec):P2\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "33482", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P2\nChaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "29993", ["itemName"] = "twinblade of the phoenix", ["classPriority"] = "Paladin ( Ret):P2", ["note"] = "",},
    {["itemId"] = "30131", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P3", ["note"] = "",},
    {["itemId"] = "32260", ["itemName"] = "choker of endless nightmares", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Enh):P3\nChasseur (BM):P3\nGuerrier (Fury:P3\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "30055", ["itemName"] = "shoulderpads of the stranger", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Enh):P2\nGuerrier (Fury:P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "32323", ["itemName"] = "shadowmoon destroyers drape", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Enh):P3\nChasseur (BM):P3\nGuerrier (Fury:P3\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "30905", ["itemName"] = "midnight chestguard", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "30863", ["itemName"] = "deadly cuffs", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "32347", ["itemName"] = "grips of damnation", ["classPriority"] = "Paladin ( Ret):P3", ["note"] = "",},
    {["itemId"] = "32265", ["itemName"] = "shadow walkers cord", ["classPriority"] = "Paladin ( Ret):P3", ["note"] = "",},
    {["itemId"] = "32335", ["itemName"] = "unstoppable aggressors ring", ["classPriority"] = "Paladin ( Ret):P3", ["note"] = "",},
    {["itemId"] = "32526", ["itemName"] = "band of devastation", ["classPriority"] = "Paladin ( Ret):P3", ["note"] = "",},
    {["itemId"] = "30900", ["itemName"] = "bow stitched leggings", ["classPriority"] = "Paladin ( Ret):P3\nChaman (Enh):P3\nChasseur (Surv):P3", ["note"] = "",},
    {["itemId"] = "32366", ["itemName"] = "shadowmasters boots", ["classPriority"] = "Paladin ( Ret):P3\nChasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3\nGuerrier (Fury:P3\nDuide (Cat):P3\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "30627", ["itemName"] = "tsunami talisman", ["classPriority"] = "Paladin ( Ret):P3\nGuerrier (Fury:P2\nDuide (Cat):P3", ["note"] = "",},
    {["itemId"] = "32332", ["itemName"] = "torch of the damned", ["classPriority"] = "Paladin ( Ret):P3", ["note"] = "",},
    {["itemId"] = "32235", ["itemName"] = "cursed vision of sargeras", ["classPriority"] = "Paladin ( Ret):P5\nChaman (Enh):P3\nChasseur (BM):P3\nChasseur (Prec):P3\nGuerrier (Fury:P3\nPaladin ( Tank):P5\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "34177", ["itemName"] = "clutch of demise", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34388", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34215", ["itemName"] = "warharness of reckless fury", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34431", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34234", ["itemName"] = "shadowed gauntlets of paroxysm", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34485", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34189", ["itemName"] = "band of ruinous delight", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34180", ["itemName"] = "felfury legplates", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34561", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34472", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "34183", ["itemName"] = "shivering felspine", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "33590", ["itemName"] = "cloak of fiends", ["classPriority"] = "Paladin ( Ret):P5\nPaladin ( Tank):P5", ["note"] = "",},
    {["itemId"] = "30228", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2", ["note"] = "",},
    {["itemId"] = "33066", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2", ["note"] = "",},
    {["itemId"] = "30230", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "30222", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "30229", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "32790", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2", ["note"] = "",},
    {["itemId"] = "32810", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2", ["note"] = "",},
    {["itemId"] = "30834", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2\nDuide (Cat):P1", ["note"] = "",},
    {["itemId"] = "32658", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2", ["note"] = "",},
    {["itemId"] = "29994", ["itemName"] = "thalassian wildercloak", ["classPriority"] = "Druide (Tank):P2\nChaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P3\nChasseur (Prec):P2\nChasseur (Prec):P3\nDuide (Cat):P3", ["note"] = "",},
    {["itemId"] = "28658", ["itemName"] = "terestians stranglestaff", ["classPriority"] = "Druide (Tank):P2\nDuide (Cat):P2", ["note"] = "",},
    {["itemId"] = "32387", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Tank):P2\nDruide (Equi):P2", ["note"] = "",},
    {["itemId"] = "28570", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "24250", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1\nDémo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P1", ["note"] = "",},
    {["itemId"] = "28799", ["itemName"] = "belt of divine inspiration", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "28793", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1\nMage(Arcane):P1\nDruide (Equi):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29352", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "29350", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "24266", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2", ["note"] = "",},
    {["itemId"] = "21869", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29992", ["itemName"] = "royal cloak of the sunstriders", ["classPriority"] = "Prêtre (SP):P2\nMage(Arcane):P2\nPaladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "21871", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29918", ["itemName"] = "mindstorm wristbands", ["classPriority"] = "Prêtre (SP):P2\nDruide (Equi):P2\nChaman (Elem):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "28780", ["itemName"] = "soul eaters handwraps", ["classPriority"] = "Prêtre (SP):P2\nChaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "30038", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2\nDruide (Equi):P2\nChaman (Elem):P2\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P2\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "24262", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2\nChaman (Elem):P1\nDémo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P1\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "30109", ["itemName"] = "ring of endless coils", ["classPriority"] = "Prêtre (SP):P2\nDruide (Equi):P2\nChaman (Elem):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "29922", ["itemName"] = "band of alar", ["classPriority"] = "Prêtre (SP):P2", ["note"] = "",},
    {["itemId"] = "29370", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2\nDruide (Equi):P1\nPaladin ( Tank):P3\nChaman (Elem):P3\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "28770", ["itemName"] = "nathrezim mindblade", ["classPriority"] = "Prêtre (SP):P2\nMage(Arcane):P1\nChaman (Elem):P1", ["note"] = "",},
    {["itemId"] = "29272", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P2", ["note"] = "",},
    {["itemId"] = "29982", ["itemName"] = "wand of the forgotten star", ["classPriority"] = "Prêtre (SP):P2\nDémo (Affli):P3\nDémo (Destru):P2\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "31064", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "30666", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "31070", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "32590", ["itemName"] = "#REF!", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "31065", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "32586", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3\nChaman (Elem):P3\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "31061", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "32256", ["itemName"] = "waistwrap of infinity", ["classPriority"] = "Prêtre (SP):P3\nMage(Arcane):P3", ["note"] = "",},
    {["itemId"] = "30916", ["itemName"] = "leggings of channeled elements", ["classPriority"] = "Prêtre (SP):P3\nChaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "28585", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "32527", ["itemName"] = "ring of ancient knowledge", ["classPriority"] = "Prêtre (SP):P3\nMage(Arcane):P3\nChaman (Elem):P3\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "31856", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P3\nDémo (Affli):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "28789", ["itemName"] = "eye of magtheridon", ["classPriority"] = "Prêtre (SP):P3\nPaladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32374", ["itemName"] = "zhardoom greatstaff of the devourer", ["classPriority"] = "Prêtre (SP):P3\nChaman (Elem):P3\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "32343", ["itemName"] = "wand of prismatic focus", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "24312", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "30280", ["itemName"] = "#REF!", ["classPriority"] = "Prêtre (SP):P2", ["note"] = "",},
    {["itemId"] = "24309", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "24297", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "21914", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1", ["note"] = "",},
    {["itemId"] = "32754", ["itemName"] = "pattern bracers of nimble thought", ["classPriority"] = "Prêtre (SP):P3", ["note"] = "",},
    {["itemId"] = "21870", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (SP):P1\nDémo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "28765", ["itemName"] = "stainless cloak of the pure hearted", ["classPriority"] = "Chaman (Resto):P1\nPaladin (Holy):P1\nDruide (Heal):P1", ["note"] = "",},
    {["itemId"] = "28763", ["itemName"] = "jade ring of the everliving", ["classPriority"] = "Chaman (Resto):P1\nChaman (Resto):P2\nPaladin (Holy):P1\nDruide (Heal):P1", ["note"] = "",},
    {["itemId"] = "28771", ["itemName"] = "lights justice", ["classPriority"] = "Chaman (Resto):P1\nPaladin (Holy):P1\nDruide (Heal):P1\nPrêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "29458", ["itemName"] = "aegis of the vindicator", ["classPriority"] = "Chaman (Resto):P1\nPaladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "30018", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P2\nDruide (Heal):P2\nPrêtre (Holy):P2", ["note"] = "",},
    {["itemId"] = "30168", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P2", ["note"] = "",},
    {["itemId"] = "29989", ["itemName"] = "sunshower light cloak", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P2\nDruide (Heal):P2\nPrêtre (Holy):P2\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "30164", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P2", ["note"] = "",},
    {["itemId"] = "29991", ["itemName"] = "sunhawk leggings", ["classPriority"] = "Chaman (Resto):P2", ["note"] = "",},
    {["itemId"] = "30092", ["itemName"] = "orca hide boots", ["classPriority"] = "Chaman (Resto):P2\nDruide (Heal):P2", ["note"] = "",},
    {["itemId"] = "30108", ["itemName"] = "lightfathom scepter", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P2\nDruide (Heal):P2", ["note"] = "",},
    {["itemId"] = "29923", ["itemName"] = "talisman of the sun king", ["classPriority"] = "Chaman (Resto):P2\nPrêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "29376", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P2\nPaladin (Holy):P1\nDruide (Heal):P1\nPrêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "30166", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P3", ["note"] = "",},
    {["itemId"] = "32370", ["itemName"] = "nadinas pendant of purity", ["classPriority"] = "Chaman (Resto):P3\nPaladin (Holy):P3\nPrêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "31022", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P3", ["note"] = "",},
    {["itemId"] = "32524", ["itemName"] = "shroud of the highborne", ["classPriority"] = "Chaman (Resto):P3\nPaladin (Holy):P3\nPrêtre (Holy):P3\nMage(Arcane):P3\nChaman (Elem):P3\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3", ["note"] = "",},
    {["itemId"] = "31016", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P3", ["note"] = "",},
    {["itemId"] = "30047", ["itemName"] = "blackfathom warbands", ["classPriority"] = "Chaman (Resto):P3\nPaladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "29976", ["itemName"] = "worldstorm gauntlets", ["classPriority"] = "Chaman (Resto):P3", ["note"] = "",},
    {["itemId"] = "30030", ["itemName"] = "girdle of fallen stars", ["classPriority"] = "Chaman (Resto):P3\nPaladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "32528", ["itemName"] = "blessed band of karabor", ["classPriority"] = "Chaman (Resto):P3\nPaladin (Holy):P3\nPrêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "30873", ["itemName"] = "stillwater boots", ["classPriority"] = "Chaman (Resto):P3", ["note"] = "",},
    {["itemId"] = "32496", ["itemName"] = "memento of tyrande", ["classPriority"] = "Chaman (Resto):P3\nPaladin (Holy):P3\nDruide (Heal):P4\nPrêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "28190", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P3", ["note"] = "",},
    {["itemId"] = "33464", ["itemName"] = "hex lords voodoo pauldrons", ["classPriority"] = "Chaman (Resto):P4", ["note"] = "",},
    {["itemId"] = "33592", ["itemName"] = "cloak of ancient rituals", ["classPriority"] = "Chaman (Resto):P4", ["note"] = "",},
    {["itemId"] = "33469", ["itemName"] = "hauberk of the empires champion", ["classPriority"] = "Chaman (Resto):P4", ["note"] = "",},
    {["itemId"] = "30869", ["itemName"] = "howling wind bracers", ["classPriority"] = "Chaman (Resto):P4", ["note"] = "",},
    {["itemId"] = "32328", ["itemName"] = "botanists gloves of growth", ["classPriority"] = "Chaman (Resto):P4\nDruide (Heal):P4", ["note"] = "",},
    {["itemId"] = "30895", ["itemName"] = "angelistas sash", ["classPriority"] = "Chaman (Resto):P4", ["note"] = "",},
    {["itemId"] = "30912", ["itemName"] = "leggings of eternity", ["classPriority"] = "Chaman (Resto):P4\nPrêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "33471", ["itemName"] = "two toed sandals", ["classPriority"] = "Chaman (Resto):P4\nPaladin (Holy):P4", ["note"] = "",},
    {["itemId"] = "32500", ["itemName"] = "crystal spire of karabor", ["classPriority"] = "Chaman (Resto):P4\nPaladin (Holy):P3\nDruide (Heal):P4\nPrêtre (Holy):P3\nPrêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "30882", ["itemName"] = "bastion of light", ["classPriority"] = "Chaman (Resto):P4", ["note"] = "",},
    {["itemId"] = "31012", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P5", ["note"] = "",},
    {["itemId"] = "33281", ["itemName"] = "brooch of natures mercy", ["classPriority"] = "Chaman (Resto):P5\nPaladin (Holy):P4\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34208", ["itemName"] = "equilibrium epaulets", ["classPriority"] = "Chaman (Resto):P5", ["note"] = "",},
    {["itemId"] = "34212", ["itemName"] = "sunglow vest", ["classPriority"] = "Chaman (Resto):P5\nDruide (Heal):P5", ["note"] = "",},
    {["itemId"] = "34438", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P5", ["note"] = "",},
    {["itemId"] = "34409", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P5", ["note"] = "",},
    {["itemId"] = "34543", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P5", ["note"] = "",},
    {["itemId"] = "34383", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P5\nPaladin (Holy):P5", ["note"] = "",},
    {["itemId"] = "34565", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Resto):P5", ["note"] = "",},
    {["itemId"] = "34430", ["itemName"] = "glimmering naaru sliver", ["classPriority"] = "Chaman (Resto):P5\nPaladin (Holy):P5\nDruide (Heal):P5\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34199", ["itemName"] = "archons gavel", ["classPriority"] = "Chaman (Resto):P5\nPaladin (Holy):P5\nDruide (Heal):P5\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34206", ["itemName"] = "book of highborne hymns", ["classPriority"] = "Chaman (Resto):P5\nPaladin (Holy):P5\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "28822", ["itemName"] = "teeth of gruul", ["classPriority"] = "Paladin (Holy):P1\nPrêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "29062", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "29061", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "29064", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "28512", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "28505", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "28733", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "28748", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "28569", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "28790", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1\nPrêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28727", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P1", ["note"] = "",},
    {["itemId"] = "30136", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30138", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30134", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30112", ["itemName"] = "glorious gauntlets of crestfall", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30137", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "29920", ["itemName"] = "phoenix ring of rebirth", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30027", ["itemName"] = "boots of courage unending", ["classPriority"] = "Paladin (Holy):P2", ["note"] = "",},
    {["itemId"] = "30988", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "32354", ["itemName"] = "crown of empowered fate", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "30996", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "30992", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "30862", ["itemName"] = "blessed adamantite bracers", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "30897", ["itemName"] = "girdle of hope", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "30994", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "32243", ["itemName"] = "pearl inlaid boots", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "32255", ["itemName"] = "felstone bulwark", ["classPriority"] = "Paladin (Holy):P3", ["note"] = "",},
    {["itemId"] = "34209", ["itemName"] = "spaulders of reclamation", ["classPriority"] = "Paladin (Holy):P5\nDruide (Heal):P5", ["note"] = "",},
    {["itemId"] = "34229", ["itemName"] = "garments of serene shores", ["classPriority"] = "Paladin (Holy):P5", ["note"] = "",},
    {["itemId"] = "34432", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P5", ["note"] = "",},
    {["itemId"] = "34240", ["itemName"] = "gauntlets of the soothed soul", ["classPriority"] = "Paladin (Holy):P5", ["note"] = "",},
    {["itemId"] = "34487", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P5", ["note"] = "",},
    {["itemId"] = "34559", ["itemName"] = "#N/A", ["classPriority"] = "Paladin (Holy):P5", ["note"] = "",},
    {["itemId"] = "28609", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P1", ["note"] = "",},
    {["itemId"] = "29089", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P1", ["note"] = "",},
    {["itemId"] = "29087", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P1", ["note"] = "",},
    {["itemId"] = "28521", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P1", ["note"] = "",},
    {["itemId"] = "28591", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P1", ["note"] = "",},
    {["itemId"] = "29274", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P1\nDruide (Heal):P2", ["note"] = "",},
    {["itemId"] = "30219", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P2", ["note"] = "",},
    {["itemId"] = "30221", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P2", ["note"] = "",},
    {["itemId"] = "30216", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P2", ["note"] = "",},
    {["itemId"] = "30062", ["itemName"] = "grove bands of remulos", ["classPriority"] = "Druide (Heal):P2", ["note"] = "",},
    {["itemId"] = "29984", ["itemName"] = "girdle of zaetar", ["classPriority"] = "Druide (Heal):P2", ["note"] = "",},
    {["itemId"] = "30110", ["itemName"] = "coral band of the revived", ["classPriority"] = "Druide (Heal):P2\nPrêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "32519", ["itemName"] = "belt of divine guidance", ["classPriority"] = "Druide (Heal):P3\nPrêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "29309", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P3\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "31047", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P4", ["note"] = "",},
    {["itemId"] = "31041", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P4", ["note"] = "",},
    {["itemId"] = "30868", ["itemName"] = "rejuvenating bracers", ["classPriority"] = "Druide (Heal):P4", ["note"] = "",},
    {["itemId"] = "33483", ["itemName"] = "life step belt", ["classPriority"] = "Druide (Heal):P4", ["note"] = "",},
    {["itemId"] = "32271", ["itemName"] = "kilt of immortal nature", ["classPriority"] = "Druide (Heal):P4", ["note"] = "",},
    {["itemId"] = "32609", ["itemName"] = "#REF!", ["classPriority"] = "Druide (Heal):P4", ["note"] = "",},
    {["itemId"] = "31037", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "35291", ["itemName"] = "sindorei pendant of salvation", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "32337", ["itemName"] = "shroud of forgiveness", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "34445", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "34351", ["itemName"] = "tranquil majesty wraps", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "34554", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "35733", ["itemName"] = "ring of harmonic beauty", ["classPriority"] = "Druide (Heal):P5\nPrêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34384", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "34571", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Heal):P5", ["note"] = "",},
    {["itemId"] = "30911", ["itemName"] = "scepter of purification", ["classPriority"] = "Druide (Heal):P5\nPrêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "29049", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "29054", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "29050", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28511", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28508", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "30675", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28742", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28663", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28525", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "28588", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P1", ["note"] = "",},
    {["itemId"] = "30036", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P2", ["note"] = "",},
    {["itemId"] = "30152", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "30154", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "30150", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "32516", ["itemName"] = "wraps of purification", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "30151", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "30153", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "30100", ["itemName"] = "soul strider boots", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "30080", ["itemName"] = "luminescent rod of the naaru", ["classPriority"] = "Prêtre (Holy):P3", ["note"] = "",},
    {["itemId"] = "31066", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "30871", ["itemName"] = "bracers of martyrdom", ["classPriority"] = "Prêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "30885", ["itemName"] = "archbishops slippers", ["classPriority"] = "Prêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "32363", ["itemName"] = "naaru blessed life rod", ["classPriority"] = "Prêtre (Holy):P4", ["note"] = "",},
    {["itemId"] = "31063", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34202", ["itemName"] = "shawl of wonderment", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34233", ["itemName"] = "robes of faltered light", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34435", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34342", ["itemName"] = "handguards of the dawn", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34527", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34170", ["itemName"] = "pantaloons of calming strife", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34562", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "30665", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34348", ["itemName"] = "wand of cleansing light", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "30281", ["itemName"] = "pattern belt of the long road", ["classPriority"] = "Prêtre (Holy):P2", ["note"] = "",},
    {["itemId"] = "35181", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "35189", ["itemName"] = "schematic powerheal 9000 lens", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34360", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "35202", ["itemName"] = "design amulet of flowing life", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34365", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "35207", ["itemName"] = "pattern robe of eternal light", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34367", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "35235", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "34363", ["itemName"] = "#N/A", ["classPriority"] = "Prêtre (Holy):P5", ["note"] = "",},
    {["itemId"] = "29076", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P1\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29079", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P1\nMage (Feu):P1", ["note"] = "",},
    {["itemId"] = "28783", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P1", ["note"] = "",},
    {["itemId"] = "30206", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "29987", ["itemName"] = "gauntlets of the sun king", ["classPriority"] = "Mage(Arcane):P2", ["note"] = "",},
    {["itemId"] = "30064", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P2", ["note"] = "",},
    {["itemId"] = "30207", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30067", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P2\nChaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "30626", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P2", ["note"] = "",},
    {["itemId"] = "30720", ["itemName"] = "serpent coil braid", ["classPriority"] = "Mage(Arcane):P2\nMage(Arcane):P5", ["note"] = "",},
    {["itemId"] = "29988", ["itemName"] = "the nexus key", ["classPriority"] = "Mage(Arcane):P2\nDruide (Equi):P2\nChaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "31056", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P3", ["note"] = "",},
    {["itemId"] = "30210", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P3\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30015", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P3\nDruide (Equi):P2\nChaman (Elem):P3\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30196", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P3", ["note"] = "",},
    {["itemId"] = "30870", ["itemName"] = "cuffs of devastation", ["classPriority"] = "Mage(Arcane):P3", ["note"] = "",},
    {["itemId"] = "31055", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "31058", ["itemName"] = "#N/A", ["classPriority"] = "Mage(Arcane):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "32239", ["itemName"] = "slippers of the seacaller", ["classPriority"] = "Mage(Arcane):P3\nChaman (Elem):P3\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "32483", ["itemName"] = "the skull of guldan", ["classPriority"] = "Mage(Arcane):P3\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "28766", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P1\nDruide (Equi):P2\nChaman (Elem):P1\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "27683", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P1\nDémo (Affli):P2\nDémo (Destru):P1\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30233", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P2", ["note"] = "",},
    {["itemId"] = "30235", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P2", ["note"] = "",},
    {["itemId"] = "30107", ["itemName"] = "vestments of the sea witch", ["classPriority"] = "Druide (Equi):P2\nDémo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30232", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P2", ["note"] = "",},
    {["itemId"] = "30234", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P2", ["note"] = "",},
    {["itemId"] = "30037", ["itemName"] = "#N/A", ["classPriority"] = "Druide (Equi):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30115", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30117", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30007", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "29925", ["itemName"] = "phoenix wing cloak", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30113", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "32515", ["itemName"] = "wristguards of determination", ["classPriority"] = "Guerrier (Tank):P2\nPaladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "30114", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30096", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30116", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "32267", ["itemName"] = "boots of the resilient", ["classPriority"] = "Guerrier (Tank):P2\nPaladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "30083", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30058", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30025", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P2", ["note"] = "",},
    {["itemId"] = "30974", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "30980", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32362", ["itemName"] = "pendant of titans", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "34010", ["itemName"] = "#REF!", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "30976", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32232", ["itemName"] = "eternium shell bracers", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32280", ["itemName"] = "gauntlets of enforcement", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32333", ["itemName"] = "girdle of stability", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "30978", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32268", ["itemName"] = "myrmidons treads", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32261", ["itemName"] = "band of the abyssal lord", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32254", ["itemName"] = "the brutalizer", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "32375", ["itemName"] = "bulwark of azzinoth", ["classPriority"] = "Guerrier (Tank):P3\nPaladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32325", ["itemName"] = "rifle of the stoic guardian", ["classPriority"] = "Guerrier (Tank):P3", ["note"] = "",},
    {["itemId"] = "29040", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "29381", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1\nChasseur (BM):P1\nChasseur (Prec):P1\nGuerrier (Fury:P1\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "29043", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "24259", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1\nChasseur (BM):P1\nChasseur (Prec):P1\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "29515", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "29517", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "28776", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "29516", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "28741", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1\nChasseur (BM):P1\nChasseur (Surv):P1\nChasseur (Prec):P1\nGuerrier (Fury:P1\nDuide (Cat):P1\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "25686", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1\nGuerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28757", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1\nChasseur (BM):P1\nChasseur (Prec):P1\nGuerrier (Fury:P2\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "29283", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "28767", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "28920", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "30190", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "30017", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P3\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "30185", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "30091", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "30189", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "30192", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "30052", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P2\nDuide (Cat):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "29383", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P2\nChasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2\nGuerrier (Fury:P1\nDuide (Cat):P2\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "32944", ["itemName"] = "talon of the phoenix", ["classPriority"] = "Chaman (Enh):P2\nChasseur (BM):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "29996", ["itemName"] = "rod of the sun king", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "32377", ["itemName"] = "mantle of darkness", ["classPriority"] = "Chaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "32234", ["itemName"] = "fists of mukoa", ["classPriority"] = "Chaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "32510", ["itemName"] = "softstep boots of tracking", ["classPriority"] = "Chaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "29301", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P3\nChasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3\nGuerrier (Fury:P3\nDuide (Cat):P3", ["note"] = "",},
    {["itemId"] = "32497", ["itemName"] = "stormrage signet ring", ["classPriority"] = "Chaman (Enh):P3\nChasseur (BM):P3\nChasseur (Prec):P3\nGuerrier (Fury:P3\nDuide (Cat):P3\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "32505", ["itemName"] = "madness of the betrayer", ["classPriority"] = "Chaman (Enh):P3\nChasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3\nGuerrier (Fury:P3\nDuide (Cat):P3\nVoleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "32262", ["itemName"] = "syphon of the nathrezim", ["classPriority"] = "Chaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "27815", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "30306", ["itemName"] = "pattern boots of utter darkness", ["classPriority"] = "Chaman (Enh):P2", ["note"] = "",},
    {["itemId"] = "35528", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P3", ["note"] = "",},
    {["itemId"] = "30039", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1\nGuerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "32581", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Enh):P1", ["note"] = "",},
    {["itemId"] = "28275", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Surv):P1\nChasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "27801", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Surv):P1\nChasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "29246", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Prec):P1\nDuide (Cat):P1\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "27474", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Surv):P1\nChasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "29247", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Prec):P2\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "28545", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Surv):P1\nChasseur (Prec):P1\nDuide (Cat):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "28649", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nDuide (Cat):P1\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "27846", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "28315", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "28772", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P1\nChasseur (Surv):P1\nChasseur (Prec):P1\nVoleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "30141", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "30143", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "30139", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "29966", ["itemName"] = "vambraces of ending", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2\nDuide (Cat):P2\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30140", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "29948", ["itemName"] = "claw of the phoenix", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "30105", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2\nGuerrier (Fury:P3", ["note"] = "",},
    {["itemId"] = "31006", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "31004", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "32324", ["itemName"] = "insidious bands", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3\nDuide (Cat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "31001", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "30879", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "31005", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "30901", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "30881", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "30906", ["itemName"] = "bristleblitz striker", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P3\nChasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "30302", ["itemName"] = "pattern belt of deep shadow", ["classPriority"] = "Chasseur (BM):P2\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "30040", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (BM):P3\nChasseur (Surv):P2\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "28343", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1", ["note"] = "",},
    {["itemId"] = "29382", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1", ["note"] = "",},
    {["itemId"] = "28228", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1\nChasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "25697", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1", ["note"] = "",},
    {["itemId"] = "28750", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1\nDuide (Cat):P1", ["note"] = "",},
    {["itemId"] = "28584", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1", ["note"] = "",},
    {["itemId"] = "28572", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P1", ["note"] = "",},
    {["itemId"] = "28506", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P2\nDuide (Cat):P1", ["note"] = "",},
    {["itemId"] = "30142", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P2", ["note"] = "",},
    {["itemId"] = "29924", ["itemName"] = "netherbane", ["classPriority"] = "Chasseur (Surv):P2", ["note"] = "",},
    {["itemId"] = "31003", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P3", ["note"] = "",},
    {["itemId"] = "28791", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Surv):P3\nChasseur (Prec):P2", ["note"] = "",},
    {["itemId"] = "28828", ["itemName"] = "#N/A", ["classPriority"] = "Chasseur (Prec):P1", ["note"] = "",},
    {["itemId"] = "32591", ["itemName"] = "choker of serrated blades", ["classPriority"] = "Chasseur (Prec):P3", ["note"] = "",},
    {["itemId"] = "29021", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "29023", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "29019", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28824", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28730", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28729", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "28659", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P1", ["note"] = "",},
    {["itemId"] = "30120", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "30101", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "28439", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P2", ["note"] = "",},
    {["itemId"] = "30082", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P2\nVoleur (Combat):P2", ["note"] = "",},
    {["itemId"] = "30979", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P3", ["note"] = "",},
    {["itemId"] = "30975", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P3", ["note"] = "",},
    {["itemId"] = "30861", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P3", ["note"] = "",},
    {["itemId"] = "30969", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P3", ["note"] = "",},
    {["itemId"] = "30977", ["itemName"] = "#N/A", ["classPriority"] = "Guerrier (Fury:P3", ["note"] = "",},
    {["itemId"] = "32837", ["itemName"] = "warglaive of azzinoth", ["classPriority"] = "Guerrier (Fury:P3\nVoleur (Combat):P3", ["note"] = "",},
    {["itemId"] = "32838", ["itemName"] = "warglaive of azzinoth", ["classPriority"] = "Guerrier (Fury:P3\nVoleur (Combat):P3", ["note"] = "",},
    {["itemId"] = "29100", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P1", ["note"] = "",},
    {["itemId"] = "28672", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P1\nVoleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "29096", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P1", ["note"] = "",},
    {["itemId"] = "29390", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P1\nDuide (Cat):P3", ["note"] = "",},
    {["itemId"] = "30223", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P2", ["note"] = "",},
    {["itemId"] = "8345", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "24114", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "31048", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "31042", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "31034", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "31044", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "30883", ["itemName"] = "#N/A", ["classPriority"] = "Duide (Cat):P3", ["note"] = "",},
    {["itemId"] = "29068", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "28516", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "27550", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "29252", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "28518", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "29069", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "29254", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "29279", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "28792", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P1", ["note"] = "",},
    {["itemId"] = "30125", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "33065", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "29070", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "29066", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "30124", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "28566", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "30126", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "33054", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "30095", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2\nDémo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "28825", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "29388", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P2", ["note"] = "",},
    {["itemId"] = "32521", ["itemName"] = "faceplate of the impenetrable", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "33921", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "30998", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "30991", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32279", ["itemName"] = "the seekers wristguards", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "30985", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32342", ["itemName"] = "girdle of mighty resolve", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "30995", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32245", ["itemName"] = "tide stompers greaves", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "30028", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "29297", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "30910", ["itemName"] = "#N/A", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "32368", ["itemName"] = "tome of the lightbringer", ["classPriority"] = "Paladin ( Tank):P3", ["note"] = "",},
    {["itemId"] = "28762", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29519", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1", ["note"] = "",},
    {["itemId"] = "29521", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1", ["note"] = "",},
    {["itemId"] = "29520", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1", ["note"] = "",},
    {["itemId"] = "28517", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1\nDémo (DF):P1\nMage (Feu):P1", ["note"] = "",},
    {["itemId"] = "28753", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1\nDémo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P1\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "29273", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P1", ["note"] = "",},
    {["itemId"] = "29035", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "29037", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "28797", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2\nMage (Feu):P2\nMage (Givre):P2", ["note"] = "",},
    {["itemId"] = "30169", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "30172", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "30667", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "28248", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P2", ["note"] = "",},
    {["itemId"] = "31014", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "31023", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "31017", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "31008", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "32276", ["itemName"] = "flashfire girdle", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "28785", ["itemName"] = "#N/A", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "32330", ["itemName"] = "totem of ancestral guidance", ["classPriority"] = "Chaman (Elem):P3", ["note"] = "",},
    {["itemId"] = "28963", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P2", ["note"] = "",},
    {["itemId"] = "28530", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P1", ["note"] = "",},
    {["itemId"] = "28964", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1", ["note"] = "",},
    {["itemId"] = "24256", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "28802", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P1\nDémo (Dm):P1\nDémo (DF):P1\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "28673", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P1\nDémo (Destru):P1\nDémo (Dm):P1\nDémo (DF):P1\nMage (Feu):P1\nMage (Givre):P1", ["note"] = "",},
    {["itemId"] = "30212", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2", ["note"] = "",},
    {["itemId"] = "28967", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2", ["note"] = "",},
    {["itemId"] = "28968", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2", ["note"] = "",},
    {["itemId"] = "30213", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P2\nDémo (DF):P2", ["note"] = "",},
    {["itemId"] = "28734", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P2\nDémo (Destru):P2\nDémo (Dm):P1\nDémo (Dm):P2", ["note"] = "",},
    {["itemId"] = "31051", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3", ["note"] = "",},
    {["itemId"] = "32349", ["itemName"] = "translucent spellthread necklace", ["classPriority"] = "Démo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "31054", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3", ["note"] = "",},
    {["itemId"] = "31050", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3", ["note"] = "",},
    {["itemId"] = "31053", ["itemName"] = "#N/A", ["classPriority"] = "Démo (Affli):P3\nDémo (Destru):P3\nDémo (Dm):P3\nDémo (DF):P3", ["note"] = "",},
    {["itemId"] = "21848", ["itemName"] = "#N/A", ["classPriority"] = "Démo (DF):P1\nMage (Feu):P1", ["note"] = "",},
    {["itemId"] = "21846", ["itemName"] = "#N/A", ["classPriority"] = "Démo (DF):P1\nMage (Feu):P1", ["note"] = "",},
    {["itemId"] = "29132", ["itemName"] = "#N/A", ["classPriority"] = "Démo (DF):P1\nMage (Feu):P1", ["note"] = "",},
    {["itemId"] = "21847", ["itemName"] = "#N/A", ["classPriority"] = "Démo (DF):P2\nMage (Feu):P2", ["note"] = "",},
    {["itemId"] = "29270", ["itemName"] = "#N/A", ["classPriority"] = "Démo (DF):P2\nMage (Feu):P2", ["note"] = "",},
    {["itemId"] = "32247", ["itemName"] = "ring of captured storms", ["classPriority"] = "Démo (DF):P3\nMage (Feu):P3", ["note"] = "",},
    {["itemId"] = "29044", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "27797", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "29045", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "27531", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P1\nVoleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "28438", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P1", ["note"] = "",},
    {["itemId"] = "30146", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30144", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30145", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30148", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "30450", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P2\nVoleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "28189", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P2", ["note"] = "",},
    {["itemId"] = "31030", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "31028", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "32580", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P3", ["note"] = "",},
    {["itemId"] = "31026", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "31029", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "32266", ["itemName"] = "ring of deceitful intent", ["classPriority"] = "Voleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "29949", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Combat):P3\nVoleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "28768", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "28524", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Ass):P1", ["note"] = "",},
    {["itemId"] = "29962", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Ass):P2", ["note"] = "",},
    {["itemId"] = "32471", ["itemName"] = "shard of azzinoth", ["classPriority"] = "Voleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "30103", ["itemName"] = "#N/A", ["classPriority"] = "Voleur (Ass):P3", ["note"] = "",},
    {["itemId"] = "28411", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P1", ["note"] = "",},
    {["itemId"] = "32494", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P2", ["note"] = "",},
    {["itemId"] = "30024", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P2", ["note"] = "",},
    {["itemId"] = "32525", ["itemName"] = "cowl of the illidari high lord", ["classPriority"] = "Mage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "32589", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P3", ["note"] = "",},
    {["itemId"] = "31059", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "32331", ["itemName"] = "cloak of the illidari council", ["classPriority"] = "Mage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "31057", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "29305", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Feu):P3\nMage (Givre):P3", ["note"] = "",},
    {["itemId"] = "27462", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Givre):P1", ["note"] = "",},
    {["itemId"] = "29080", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Givre):P1", ["note"] = "",},
    {["itemId"] = "30205", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Givre):P2", ["note"] = "",},
    {["itemId"] = "29269", ["itemName"] = "#N/A", ["classPriority"] = "Mage (Givre):P2", ["note"] = "",},
    }